# -*- coding: utf-8 -*-
"""Projek Data Wrangling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wOVxWoyey96g0MalMQdMz53n9Wbz_7d_

# **Membaca File**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('seaborn-v0_8')

"""## PM2.5

"""

pm25_raw = pd.read_csv("pm25-air-pollution.csv")

pm25_raw.info()

pm25_raw

"""## GDP"""

gdp_raw = pd.read_csv("API_NY.GDP.PCAP.CD_DS2_en_csv_v2_252771.csv", skiprows=4)

gdp_raw.info()

gdp_raw.head()

"""## Population"""

population_raw = pd.read_csv("population.csv")

population_raw.info()

population_raw.head()

"""# **Cleaning**

### PM2.5
"""

pm25 = pm25_raw.rename(columns={
   "Entity": "Country",
    "Code": "Country_Code",
    "Concentrations of fine particulate matter (PM2.5) - Residence area type: Total": "PM25"
})

# Ambil data dari 2010 sampai 2019
pm25 = pm25[(pm25["Year"] >= 2010) & (pm25["Year"] <= 2019)]

# Save data clean
pm25.to_csv("clean_pm2,5.csv", index=False)

pm25.info()

pm25.head()

"""### GDP


"""

# Rename kolom
gdp = gdp_raw.rename(columns={
    "Country Name": "Country",
    "Country Code": "Country_Code"
})

# Hapus kolom kosong "Unnamed: 69"
gdp = gdp.drop(columns=["Unnamed: 69"], errors="ignore")

# Mengubah dari wide ke long
gdp_long = gdp.melt(
    id_vars=["Country", "Country_Code", "Indicator Name", "Indicator Code"],
    var_name="Year",
    value_name="GDP_per_capita"
)

# Ambil data dari tahun 2010 sampai 2019
gdp_long["Year"] = gdp_long["Year"].astype(int)
gdp_long = gdp_long[(gdp_long["Year"] >= 2010) & (gdp_long["Year"] <= 2019)]

# Save data clean
gdp_long.to_csv("gdp_long.csv", index=False)

gdp_long.head()

gdp_long.info()

"""### Population"""

population = population_raw.rename(columns={
    "Country Name": "Country",
    "Country Code": "Country_Code",
    "Value": "Population"
})

# Ambil data dari tahun 2010 sampai 2019
population["Year"] = population["Year"].astype(int)
population = population[(population["Year"] >= 2010) & (population["Year"] <= 2019)]

# Save data clean
population.to_csv("clean_population.csv", index=False)

population

population.info()

"""# **Pre-Processing**

PREPROCESSING PM2.5
"""

# Buang Country_Code yang kosong (biasanya region bukan negara)
pm25_pp = pm25.dropna(subset=["Country_Code"])

# Pastikan tipe data Year benar
pm25_pp["Year"] = pm25_pp["Year"].astype(int)

print("=== PM2.5 AFTER PREPROCESSING ===")
display(pm25_pp.head())
print(pm25_pp.info())

pm25_pp.to_csv("preprocessed_pm2,5.csv", index=False)

"""PREPROCESSING GDP"""

# Hapus region (yang Country_Code panjang 3 adalah negara)
gdp_pp = gdp_long[gdp_long["Country_Code"].str.len() == 3]

# Year harus integer
gdp_pp["Year"] = gdp_pp["Year"].astype(int)

print("=== GDP AFTER PREPROCESSING ===")
display(gdp_pp.head())
print(gdp_pp.info())

gdp_pp.to_csv("preprocessed_gdp.csv", index=False)

"""PREPROCESSING POPULATION"""

population_pp = population[population["Country_Code"].str.len() == 3]

population_pp["Year"] = population_pp["Year"].astype(int)
population_pp["Population"] = population_pp["Population"].astype(float)

print("=== POPULATION AFTER PREPROCESSING ===")
display(population_pp.head())
print(population_pp.info())

population_pp.to_csv("preprocessed_population.csv", index=False)

"""# **Integrasi Data**

## PM25 dengan GDP

Menyatukan kolom berbasis kolom Country dan Country_Code
"""

df = pm25.merge(gdp_long[["Country_Code", "Year", "GDP_per_capita"]],
                on=["Country_Code", "Year"],
                how="left")
df.head()

"""## PM25 dan GDP dengan Population

Menyatukan kolom berbasis kolom Country dan Country_Code
"""

final_df = df.merge(population[["Country_Code", "Year", "Population"]],
              on=["Country_Code", "Year"],
              how="left")
final_df

# Hapus baris yang memiliki nilai kosong (NaN) pada kolom PM25, GDP, atau Population
final_df = final_df.dropna(subset=["PM25", "GDP_per_capita", "Population"])
final_df

# Menyimpan File
final_df.to_csv("dataset_final_pm25_gdp_population.csv", index=False)

final_df.info()

"""# **Feature Engineering**"""

# a. Hapus kolom duplikat "Country Code"
final_df = final_df.drop(columns=["Country Code"], errors="ignore")

# b. Mengurutkan berdasarkan Country dan Year
final_df = final_df.sort_values(["Country", "Year"])

# c. Menghitung selisih tahunan untuk PM2.5, GDP per kapita, dan populasi berasal dari nilai tahun sebelumnya
final_df["PM25_YoY"] = final_df.groupby("Country")["PM25"].diff()
final_df["GDP_YoY"] = final_df.groupby("Country")["GDP_per_capita"].diff()
final_df["Population_YoY"] = final_df.groupby("Country")["Population"].diff()

# d. Menghitung persentase perubahan tahunan tiap variabel.
final_df["PM25_pct"] = final_df.groupby("Country")["PM25"].pct_change()
final_df["GDP_pct"] = final_df.groupby("Country")["GDP_per_capita"].pct_change()
final_df["Population_pct"] = final_df.groupby("Country")["Population"].pct_change()

# e. Mengelompokkan nilai PM2.5
final_df["Pollution_Level"] = pd.cut(
    final_df["PM25"],
    bins=[0, 15, 35, 100],
    labels=["Low", "Moderate", "High"]
)

# f. Mengubah variabel GDP & populasi ke skala log agar grafik lebih stabil dan data tidak terlalu melebar (skew)
final_df["log_GDP"] = np.log1p(final_df["GDP_per_capita"])
final_df["log_Population"] = np.log1p(final_df["Population"])

# g. SImpan hasil future engineering ke file baru
final_df.info()
final_df.to_csv("future engineering_dataset.csv", index=False)

final_df

"""# **Exploratory Data Analysis**"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

final_df.info()
final_df.describe()
final_df.head()

# Grafik tren PM2.5 global dari 1990–2019
plt.figure(figsize=(12,6))

# Ambil 10 negara pertama agar grafik tidak terlalu ramai
country_sample = final_df['Country'].unique()[:10]

sns.lineplot(
    data=final_df[final_df['Country'].isin(country_sample)],
    x='Year',
    y='PM25',
    hue='Country',
    linewidth=2
)

plt.title("Tren PM2.5 per Negara (2010–2019)")
plt.ylabel("PM2.5")
plt.xlabel("Tahun")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.savefig("trend_pm25.png", dpi=300, bbox_inches='tight')
plt.show()

# Korelasi GDP vs PM2.5
plt.figure(figsize=(8,5))
sns.scatterplot(data=final_df, x="GDP_per_capita", y="PM25", hue="Pollution_Level")
plt.title("Korelasi GDP per Kapita vs PM2.5")
plt.savefig("gdp_vs_pm25.png", dpi=300, bbox_inches='tight')
plt.show()

# Korelasi Population vs PM2.5
plt.figure(figsize=(8,5))
sns.scatterplot(
    data=final_df,
    x="Population",
    y="PM25",
    hue="Pollution_Level",
    alpha=0.7
)

plt.xscale("log")
plt.xlabel("Population (log scale)")
plt.ylabel("PM2.5 Concentration")
plt.title("Korelasi Populasi vs PM2.5")
plt.savefig("population_vs_pm25.png", dpi=300, bbox_inches='tight')
plt.show()

# Bar plot negara dengan polusi tertinggi
plt.figure(figsize=(8,5))
sns.boxplot(
    data=final_df,
    x="Pollution_Level",
    y="PM25",
    palette="Set2"
)

plt.title("Distribusi PM2.5 Berdasarkan Level Polusi")
plt.xlabel("Kategori Level Polusi")
plt.ylabel("PM2.5")
plt.savefig("pollution_boxplot.png", dpi=300, bbox_inches='tight')
plt.show()

# Heatmap hubungan semua variabel
plt.figure(figsize=(8,6))
sns.heatmap(final_df[["PM25","GDP_per_capita","Population"]].corr(),
            annot=True, cmap="viridis")
plt.title("Korelasi PM2.5, GDP, dan Population")
plt.savefig("correlation_heatmap.png", dpi=300, bbox_inches='tight')
plt.show()

# Menghitung rata-rata PM2.5 per-negara
top_dirty = (
    final_df.groupby("Country")["PM25"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

top_clean = (
    final_df.groupby("Country")["PM25"]
    .mean()
    .sort_values()
    .head(10)
)

# Plot negara dengan PM2.5 tertinggi
plt.figure(figsize=(12,5))
sns.barplot(x=top_dirty.values, y=top_dirty.index, palette="Reds_r")
plt.title("10 Negara dengan Rata-rata PM2.5 Tertinggi (2010–2019)")
plt.xlabel("Rata-rata PM2.5")
plt.ylabel("Negara")
plt.savefig("top_dirty_countries.png", dpi=300, bbox_inches='tight')
plt.show()

# Plot negara dengan PM2.5 terendah
plt.figure(figsize=(12,5))
sns.barplot(x=top_clean.values, y=top_clean.index, palette="Blues")
plt.title("10 Negara dengan Rata-rata PM2.5 Terendah (2010–2019)")
plt.xlabel("Rata-rata PM2.5")
plt.ylabel("Negara")
plt.savefig("top_clean_countries.png", dpi=300, bbox_inches='tight')
plt.show()